name: PowerShell Script Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  psscriptanalyzer:
    runs-on: windows-latest  # Use a Windows runner to execute PowerShell

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Copy Custom Rule for Vulnerable Ports
        shell: pwsh
        run: |
          # Copy the custom rule from the root of the repository
          New-Item -Path "$env:USERPROFILE\Documents\PowerShell\Modules\VulnerablePortsRule.psm1" -ItemType File -Force
          Set-Content -Path "$env:USERPROFILE\Documents\PowerShell\Modules\VulnerablePortsRule.psm1" -Value "$(cat VulnerablePortsRule.psm1)"

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          # Import the required modules
          Import-Module PSScriptAnalyzer
          Write-Host "PSScriptAnalyzer Module Loaded"
      
          # Path to the settings file
          $settingsFile = "$env:GITHUB_WORKSPACE\psscriptanalyzer-settings.psd1"
      
          # Ensure the settings file exists
          if (Test-Path $settingsFile) {
            Write-Host "Settings file loaded from: $settingsFile"
          } else {
            Write-Error "Settings file not found at $settingsFile"
          }
      
          # Run PSScriptAnalyzer with the custom rule from the settings file
          Invoke-ScriptAnalyzer -Path . -Settings $settingsFile | Out-File -FilePath psscriptanalyzer-results.txt
      
          # Optionally, print the results to the console
          Get-Content psscriptanalyzer-results.txt
        

      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: psscriptanalyzer-results
          path: psscriptanalyzer-results.txt
    
