name: PowerShell Script Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  psscriptanalyzer:
    runs-on: windows-latest  # Use a Windows runner to execute PowerShell
  

    steps:
      - name: Check PowerShell version
        shell: pwsh
        run: |
          # Output the PowerShell version
          $PSVersionTable.PSVersion 
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Copy Custom Rule for Vulnerable Ports
        shell: pwsh
        run: |
          # Copy the custom rule from the root of the repository
          New-Item -Path "$env:USERPROFILE\Documents\PowerShell\Modules\CommunityAnalyzerRules.psm1" -ItemType File -Force
          Set-Content -Path "$env:USERPROFILE\Documents\PowerShell\Modules\CommunityAnalyzerRules.psm1" -Value "$(cat VulnerablePortsRule.psm1)"

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          # Import the required modules
          Import-Module PSScriptAnalyzer
          Write-Host "PSScriptAnalyzer Module Loaded"
      
          # Run PSScriptAnalyzer with the custom rule from the settings file
          Invoke-ScriptAnalyzer -Path . -Recurse -CustomRulePath CommunityAnalyzerRules.psm1 -IncludeDefaultRules
    
