name: PowerShell Script Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  psscriptanalyzer:
    runs-on: windows-latest  # Use a Windows runner to execute PowerShell
  

    steps:

      - name: Checkout repository with PowerShell scripts
        uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          # Import the required modules
          Import-Module PSScriptAnalyzer
          Write-Host "PSScriptAnalyzer Module Loaded"
      
          # Run PSScriptAnalyzer with the custom rule from the settings file
          Invoke-ScriptAnalyzer -Path . -Recurse -Settings '.\security-settings\PSScriptAnalyzerSettings.psd1'
    
